services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile  # Правильный путь к Dockerfile
        volumes:
            - .:/var/www
            - /home/miet/projects/weather-bot/database:/var/www/database
        environment:
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/database/database.sqlite
            - REDIS_HOST=redis
            - REDIS_PASSWORD=null
            - REDIS_PORT=6379
        depends_on:
            - redis
#        ports:
#            - "9000:9000"  # PHP-FPM порт

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"  # Открываем 80 порт наружу (если нужно тестировать без ngrok)
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        depends_on:
            - app

    ngrok:
        image: ngrok/ngrok:latest
        command:
            - "http"
            - "nginx:80"  # Теперь ngrok проксирует в nginx, а не в PHP-FPM
            - "--log=stdout"  # Добавляем логи в консоль
        environment:
            NGROK_AUTHTOKEN: ${NGROK_AUTH_TOKEN}  # Убедитесь, что переменная есть в .env
        depends_on:
            - nginx  # Зависит от nginx, а не от app
        ports:
            - "4040:4040"  # Веб-интерфейс ngrok
        restart: unless-stopped

